const express = require("express")

const router = express.Router()

const userRoutes = require("../routes/user_routes/user.routes")
const booksRoutes = require("./book_routes/book.routes")
const categoryRoutes = require("./category_routes/category.routes")
const contactRoutes = require("./contact_routes/contact.routes")
const accountRoutes = require("./account_routes/account.routes")
const transactionRoutes = require("./transaction_routes/transaction.routes")
const noteRoutes = require("./note_routes/notes.routes")
const feedbackRoutes = require("./feedback_routes/feedback.routes")
const transaReportRoutes = require('./report_routes/report.routes')
const notificatinRoutes = require("./notification_routes/notification.routes")
const dashboardRoutes = require("./dashboard_routes/dashboard.routes")
const viewTransRoutes = require('./admin_routes/admin.routes')
const accAssignByAdminRoutes = require('./admin_routes/acc_assigned_admin.routes')

router.use("/",userRoutes)
router.use("/",booksRoutes)
router.use("/",categoryRoutes)
router.use("/",contactRoutes)
router.use("/",accountRoutes)
router.use("/",transactionRoutes)
router.use("/",noteRoutes)
router.use("/",feedbackRoutes)
router.use("/",transaReportRoutes)
router.use("/",notificatinRoutes)
router.use("/",dashboardRoutes)
router.use("/",viewTransRoutes)
router.use("/",accAssignByAdminRoutes)
module.exports = router